public enum SoundType {
  MissileLaunch,
  MissileHit,
  MissileHitBarrier,
  MissileExplosion,
  MissileBounce,
  MissileBounceWrongShield,
  EnemyExplosion,
  EnemyHit,
  PlayerExplosion,
  GameStart,
  LevelCompleted,
  GameWon,
  GameOver,
  ButtonClick,
}